# Generated by Django 2.2.1 on 2019-05-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('to_whom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('measurement', models.CharField(choices=[('P', 'P'), ('KG', 'KG'), ('M', 'M'), ('KT', 'KT')], default='P', max_length=2)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Order')),
            ],
        ),
    ]
