# Generated by Django 2.2.1 on 2019-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('м', 'м'), ('кт', 'кт')], default='шт', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
